In [ ]:
import numpy as np

# Creation of NumPy Arrays

In [ ]:
a=np.array([2,3,4])
a

array([2, 3, 4])

In [ ]:
b = np.array([(1,2,3), (4,5,6)],dtype=float)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
d = np.arange(0,9,2)
print(d)

[0 2 4 6 8]


In [ ]:
xc=np.linspace(0,2,9)
print(xc)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
a1=np.ones((4,3))
print(a1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a2=np.full((3,3),7)
print(a2)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
a2=np.eye((3))
a2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a3=np.zeros((3,4))
a3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a4=np.empty((3,3))
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Attributes

In [ ]:
a1.size

12

In [ ]:
a1.shape

(4, 3)

In [ ]:
len(a1)

4

In [ ]:
print(a1.dtype.name)

float64


# Arithmetic Operations

In [ ]:
a

array([2, 3, 4])

In [ ]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
np.sqrt(a)

array([1.41421356, 1.73205081, 2.        ])

In [ ]:
np.add(a,b)

array([[ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [ ]:
np.subtract(a,b)

array([[ 1.,  1.,  1.],
       [-2., -2., -2.]])

In [ ]:
np.multiply(a,b)

array([[ 2.,  6., 12.],
       [ 8., 15., 24.]])

In [ ]:
np.divide(a,2)

array([1. , 1.5, 2. ])

In [ ]:
np.divide(a,0)

<ipython-input-22-279d112e30e8>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(a,0)


array([inf, inf, inf])

In [ ]:
np.sqrt(a)

array([1.41421356, 1.73205081, 2.        ])

In [ ]:
np.exp(a)

array([ 7.3890561 , 20.08553692, 54.59815003])

In [ ]:
np.sin(a)

array([ 0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.cos(a)

array([-0.41614684, -0.9899925 , -0.65364362])

In [ ]:
np.log(a)

array([0.69314718, 1.09861229, 1.38629436])

# Slicing

In [ ]:
print(a[0:2])

[2 3]


In [ ]:
c=np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
c[-1:-5:-1]

array([9, 8, 7, 6])

# Comparison

In [ ]:
c[c<5]

array([1, 2, 3, 4])

In [ ]:
a==b

array([[False, False, False],
       [False, False, False]])

In [ ]:
a<b

array([[False, False, False],
       [ True,  True,  True]])

In [ ]:
a>=b

array([[ True,  True,  True],
       [False, False, False]])

In [ ]:
d

array([0, 2, 4, 6, 8])

In [ ]:
d>1

array([False,  True,  True,  True,  True])

# Aggregate Functions

In [ ]:
print(a)

[2 3 4]


In [ ]:
np.sum(a)

9

In [ ]:
np.mean(a)

3.0

In [ ]:
np.median(a)

3.0

In [ ]:
np.corrcoef(a)

1.0

In [ ]:
np.var(a)

0.6666666666666666

In [ ]:
np.std(a)

0.816496580927726

In [ ]:
np.min(a)

2

# Sorting

In [ ]:
x1=np.array([1,5,2,6,3,7])
x1

array([1, 5, 2, 6, 3, 7])

In [ ]:
x1.sort()
x1

array([1, 2, 3, 5, 6, 7])

# Miscellaneous

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a=np.array([1,2,3,4,5,-6])

In [ ]:
a=a.reshape((3,2))

In [ ]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5, -6]])

In [ ]:
a.transpose()

array([[ 1,  3,  5],
       [ 2,  4, -6]])

In [ ]:
a.flatten()

array([ 1,  2,  3,  4,  5, -6])

In [ ]:
print(a)

[[ 1  2]
 [ 3  4]
 [ 5 -6]]


In [ ]:
np.sign(a)

array([[ 1,  1],
       [ 1,  1],
       [ 1, -1]])

In [ ]:
print(np.sin(np.pi/2))

1.0


In [ ]:
np.e

2.718281828459045

In [ ]:
np.pi

3.141592653589793

In [ ]:
a=np.random.rand(6)

In [ ]:
a

array([0.30573851, 0.67632259, 0.77208678, 0.56196248, 0.37639205,
       0.92881404])

In [ ]:
np.random.random((4,4))

array([[0.6385554 , 0.01290226, 0.62159424, 0.66825953],
       [0.90165387, 0.99491797, 0.80009539, 0.81738981],
       [0.0020779 , 0.53482536, 0.79472932, 0.66372133],
       [0.12621466, 0.54369042, 0.35086954, 0.37141027]])

In [ ]:
np.random.randint(9)

4

In [ ]:
np.random.randint(4,9)

5